import { ReportData, ExportOptions } from '@/lib/types';

// Note: Install 'xlsx' package with: npm install xlsx

export function exportReportToExcel(reportData: ReportData, options: ExportOptions) {
  try {
    // Create workbook structure manually (fallback for xlsx-lite)
    let csvContent = '';

    // Header with branding
    csvContent += `Dynamic CRM - ${options.branding.companyName}\n`;
    csvContent += `Report Generated: ${reportData.generatedAt.toLocaleString()}\n`;
    csvContent += `Generated By: ${reportData.generatedBy}\n`;
    csvContent += `Timeframe: ${reportData.timeframe}\n\n`;

    // Summary
    csvContent += `REPORT SUMMARY\n`;
    csvContent += `Report Type,${reportData.title}\n`;
    csvContent += `Total Records,${reportData.consolidated?.totalRecords || 'N/A'}\n\n`;

    // Module-wise data
    reportData.modules.forEach(module => {
      csvContent += `${module.name}\n`;
      csvContent += `Total Records,${module.summary.totalRecords}\n`;
      csvContent += `Active Records,${module.summary.activeRecords}\n`;
      csvContent += `Completed Records,${module.summary.completedRecords}\n`;
      csvContent += `Pending Records,${module.summary.pendingRecords}\n`;

      // Add metrics
      if (Object.keys(module.summary.metrics).length > 0) {
        csvContent += `\nMetrics:\n`;
        Object.entries(module.summary.metrics).forEach(([key, value]) => {
          csvContent += `${key},${value}\n`;
        });
      }

      // Add detailed data if present
      if (module.data && module.data.length > 0) {
        csvContent += `\nDetailed Data:\n`;
        const headers = Object.keys(module.data[0]);
        csvContent += headers.join(',') + '\n';
        module.data.forEach(item => {
          csvContent += headers.map(h => {
            const value = item[h];
            if (typeof value === 'object') {
              return JSON.stringify(value).replace(/,/g, ';');
            }
            return value;
          }).join(',') + '\n';
        });
      }

      csvContent += '\n\n';
    });

    // Create blob and trigger download
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);

    link.setAttribute('href', url);
    link.setAttribute('download', `report_${new Date().getTime()}.csv`);
    link.style.visibility = 'hidden';

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    return { success: true, message: 'Report exported to CSV successfully.' };
  } catch (error) {
    console.error('Failed to export report to Excel:', error);
    return { success: false, message: 'Failed to export report.' };
  }
}

// Enhanced Excel export with XLSX library (when available)
export async function exportReportToExcelAdvanced(reportData: ReportData, options: ExportOptions) {
  try {
    // Check if xlsx is available - fallback to CSV if not
    try {
      // Using dynamic import with type checking
      const xlsxModule = await import('xlsx' as any) as any;
      const XLSX = xlsxModule.default || xlsxModule;
      
      const workbook = XLSX.utils.book_new();

      // Summary Sheet
      const summaryData = [
        ['Dynamic CRM Report'],
        [`Report: ${reportData.title}`],
        [`Generated: ${reportData.generatedAt.toLocaleString()}`],
        [`Generated By: ${reportData.generatedBy}`],
        [`Timeframe: ${reportData.timeframe}`],
        [],
        ['Total Records', reportData.consolidated?.totalRecords || 'N/A'],
      ];

      const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
      XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

      // Module sheets
      reportData.modules.forEach((module: any) => {
        const sheetData: any[] = [
          [module.name],
          ['Metric', 'Value'],
          ['Total Records', module.summary.totalRecords],
          ['Active Records', module.summary.activeRecords],
          ['Completed Records', module.summary.completedRecords],
          ['Pending Records', module.summary.pendingRecords],
          [],
        ];

        // Add metrics
        Object.entries(module.summary.metrics).forEach(([key, value]: any) => {
          sheetData.push([key, value]);
        });

        // Add detailed data if present
        if (module.data && module.data.length > 0) {
          sheetData.push([]);
          sheetData.push(['Detailed Data:']);
          const headers = Object.keys(module.data[0]);
          sheetData.push(headers);
          module.data.forEach((item: any) => {
            sheetData.push(headers.map((h: string) => {
              const value = item[h];
              if (typeof value === 'object' && value !== null) {
                return JSON.stringify(value);
              }
              return value || '';
            }));
          });
        }

        const sheet = XLSX.utils.aoa_to_sheet(sheetData);
        sheet['!cols'] = [{ wch: 20 }, { wch: 30 }];
        XLSX.utils.book_append_sheet(workbook, sheet, module.name.slice(0, 31));
      });

      // Write file
      XLSX.writeFile(workbook, `dynamic-crm-report_${new Date().getTime()}.xlsx`);

      return { success: true, message: 'Report exported to Excel successfully.' };
    } catch (xlsxError) {
      console.warn('XLSX library not available, using CSV fallback:', xlsxError);
      return exportReportToExcel(reportData, options);
    }
  } catch (error) {
    console.error('Failed to export report to Excel:', error);
    return { success: false, message: 'Failed to export report.' };
  }
}
