import { ReportData, ExportOptions } from '@/lib/types';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export function exportReportToPDF(reportData: ReportData, options: ExportOptions) {
  try {
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    let yPosition = 20;
    const pageHeight = pdf.internal.pageSize.height;
    const pageWidth = pdf.internal.pageSize.width;
    const margin = 15;
    const contentWidth = pageWidth - 2 * margin;

    // Helper function to add new page if needed
    const checkNewPage = (spaceNeeded: number) => {
      if (yPosition + spaceNeeded > pageHeight - 20) {
        pdf.addPage();
        yPosition = 20;
      }
    };

    // Header with branding
    pdf.setFont('Helvetica', 'bold');
    pdf.setFontSize(20);
    pdf.text('Dynamic CRM Report', margin, yPosition);
    yPosition += 10;

    pdf.setFont('Helvetica', 'normal');
    pdf.setFontSize(10);
    pdf.text(`Company: ${options.branding.companyName}`, margin, yPosition);
    yPosition += 5;
    if (options.branding.companyEmail) {
      pdf.text(`Email: ${options.branding.companyEmail}`, margin, yPosition);
      yPosition += 5;
    }
    if (options.branding.companyPhone) {
      pdf.text(`Phone: ${options.branding.companyPhone}`, margin, yPosition);
      yPosition += 5;
    }

    // Report details
    yPosition += 5;
    pdf.setFont('Helvetica', 'bold');
    pdf.setFontSize(12);
    pdf.text('Report Details', margin, yPosition);
    yPosition += 5;

    pdf.setFont('Helvetica', 'normal');
    pdf.setFontSize(10);
    const reportDetails = [
      [`Report Type: ${reportData.title}`],
      [`Generated: ${reportData.generatedAt.toLocaleString()}`],
      [`Generated By: ${reportData.generatedBy}`],
      [`Timeframe: ${reportData.timeframe}`],
      [`Total Records: ${reportData.consolidated?.totalRecords || 'N/A'}`],
    ];

    reportDetails.forEach(detail => {
      pdf.text(detail[0], margin, yPosition);
      yPosition += 5;
    });

    // Module Reports
    reportData.modules.forEach((module, index) => {
      checkNewPage(15);

      yPosition += 5;
      pdf.setFont('Helvetica', 'bold');
      pdf.setFontSize(12);
      pdf.text(`${module.name} Report`, margin, yPosition);
      yPosition += 5;

      // Summary metrics table
      const summaryTable = [
        ['Metric', 'Value'],
        ['Total Records', module.summary.totalRecords.toString()],
        ['Active Records', module.summary.activeRecords.toString()],
        ['Completed Records', module.summary.completedRecords.toString()],
        ['Pending Records', module.summary.pendingRecords.toString()],
      ];

      // Add additional metrics
      Object.entries(module.summary.metrics).forEach(([key, value]) => {
        summaryTable.push([key, value.toString()]);
      });

      (pdf as any).autoTable({
        startY: yPosition,
        head: [summaryTable[0]],
        body: summaryTable.slice(1),
        margin: { left: margin, right: margin },
        theme: 'grid',
        headStyles: {
          fillColor: [59, 130, 246],
          textColor: 255,
          fontStyle: 'bold',
        },
        bodyStyles: {
          textColor: 0,
        },
        alternateRowStyles: {
          fillColor: [240, 240, 240],
        },
      });

      yPosition = (pdf as any).lastAutoTable.finalY + 5;

      // Detailed data if available
      if (module.data && module.data.length > 0) {
        checkNewPage(15);

        yPosition += 5;
        pdf.setFont('Helvetica', 'bold');
        pdf.setFontSize(11);
        pdf.text('Detailed Data', margin, yPosition);
        yPosition += 5;

        const headers = Object.keys(module.data[0]).slice(0, 5); // Limit columns for readability
        const detailedTable = [headers];

        module.data.slice(0, 50).forEach(item => {
          detailedTable.push(
            headers.map(h => {
              const value = item[h];
              if (typeof value === 'object' && value !== null) {
                return JSON.stringify(value).substring(0, 20);
              }
              return (value || '').toString().substring(0, 20);
            })
          );
        });

        (pdf as any).autoTable({
          startY: yPosition,
          head: [detailedTable[0]],
          body: detailedTable.slice(1),
          margin: { left: margin, right: margin },
          theme: 'grid',
          headStyles: {
            fillColor: [107, 114, 128],
            textColor: 255,
            fontStyle: 'bold',
            fontSize: 9,
          },
          bodyStyles: {
            textColor: 0,
            fontSize: 8,
          },
          alternateRowStyles: {
            fillColor: [250, 250, 250],
          },
        });

        yPosition = (pdf as any).lastAutoTable.finalY + 5;
      }
    });

    // Footer
    const totalPages = (pdf as any).internal.pages.length - 1;
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFont('Helvetica', 'normal');
      pdf.setFontSize(8);
      pdf.text(
        `Page ${i} of ${totalPages}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
    }

    // Download
    pdf.save(`dynamic-crm-report_${new Date().getTime()}.pdf`);

    return { success: true, message: 'Report exported to PDF successfully.' };
  } catch (error) {
    console.error('Failed to export report to PDF:', error);
    return { success: false, message: 'Failed to export report.' };
  }
}

declare global {
  interface jsPDF {
    autoTable: (options: any) => void;
    lastAutoTable: { finalY: number };
  }
}
